name: Env based vars/secrets selection

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Select Environment
        required: true
        options:
          - dev
          - test
          - stage
          - prod


jobs:
  show-env-var:
    runs-on: ubuntu-latest

    # This binds the environment from GitHub settings
    environment: ${{ inputs.env }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Print selected environment
        run: |
          echo "Selected environment is: ${{ inputs.env }}"

      - name: Print environment variable
        run: |
          echo "VAR2 is:  ${{ vars.VAR2 }}"
      

      
