name: AI Gateway Performance Suite Tests

on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Select Environment
        required: true
        options:
          - dev
          - test
          - stage
          - prod


jobs:
  show-secrets:
    runs-on: ubuntu-latest

    # Use the selected environment to bind secrets
    environment: ${{ inputs.env }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Print environment info
        run: |
          echo "Running in environment: ${{ inputs.env }}"

      - name: Show envv var (demo only)
        run: |
          echo "secret2: $SECRET2"
      

      
